const test = require('node:test');
const assert = require('node:assert/strict');
const { randomBytes } = require('node:crypto');
const { Pool } = require('pg');
const { pool: configurationPool } = require('../config/db');
const { createApp } = require('../src/app');
const { ensureAccessSchema } = require('../src/security/schema');
const { hashPassword, digest } = require('../src/security/access');

test('Usuarios, permisos, solicitudes y auditoría con PostgreSQL aislado', { timeout: 60000 }, async t => {
  const schema = 'arena_access_test_' + process.pid + '_' + randomBytes(5).toString('hex');
  assert.match(schema, /^arena_access_test_\d+_[a-f0-9]{10}$/);
  const connectionOptions = { ...configurationPool.options, password: configurationPool.options.password };
  const maintenance = new Pool({ ...connectionOptions, max: 1 });
  const pool = new Pool({ ...connectionOptions, options: '-c search_path=' + schema, max: 8 });
  let server;
  let observer = null;
  const watchedPool = {
    connect: () => pool.connect(),
    query: async (sql, values) => {
      const result = await pool.query(sql, values);
      if (observer && sql.startsWith('SELECT u.*,s.solo_cambio_password FROM sesiones_usuario') && values[0]===observer.hash) {
        const done = observer.resolve; observer = null; done();
      }
      return result;
    },
  };
  const password = 'Arena-test-928!';
  let adminToken, admin, mesa, mesaToken, referee, refereeToken, anotherMesa, anotherToken, championship, request;
  const championshipData = { nombre: 'Copa de prueba', modalidad: 'Ida y vuelta', categoria: 'Damas', cantidad_canchas: 3, limite_equipos: 14, hora_inicio: '19:30', duracion_partido_min: 35, descanso_entre_partidos_min: 0, activo: false };
  async function call(method, path, token, body) {
    const response = await fetch('http://127.0.0.1:' + server.address().port + '/api' + path, {
      method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) },
      body: body===undefined ? undefined : JSON.stringify(body), signal: AbortSignal.timeout(10000),
    });
    return { status: response.status, data: await response.json() };
  }
  async function expect(method, path, token, body, status) {
    const result = await call(method, path, token, body);
    assert.equal(result.status, status, method + ' ' + path + ': ' + (result.data.error || result.status));
    return result.data;
  }
  async function login(email) { return (await expect('POST','/auth/login',null,{ email,password },200)).token; }
  async function createUser(name, role, extra = {}) {
    return expect('POST','/usuarios',adminToken,{ nombre: name, email: name + '@example.test', password, rol: role, activo: true, ...extra },201);
  }
  try {
    await maintenance.query('CREATE SCHEMA ' + schema);
    await pool.query(`
      CREATE TABLE usuarios_sistema (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nombre VARCHAR(100) NOT NULL,email VARCHAR(150) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,rol VARCHAR(50) NOT NULL CHECK(rol IN ('admin','mesa','arbitro')),activo BOOLEAN DEFAULT true,created_at TIMESTAMP DEFAULT NOW());
      CREATE TABLE campeonatos (id_campeonato INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nombre VARCHAR(100) NOT NULL,modalidad VARCHAR(50) NOT NULL,categoria VARCHAR(30),cantidad_canchas INTEGER,limite_equipos INTEGER NOT NULL,hora_inicio VARCHAR(10),duracion_partido_min INTEGER,descanso_entre_partidos_min INTEGER,activo BOOLEAN);
      CREATE TABLE auditoria_logs (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,usuario_id INTEGER REFERENCES usuarios_sistema(id),accion VARCHAR(100),detalles JSONB,ip_origen VARCHAR(45),created_at TIMESTAMP DEFAULT NOW());
    `);
    for (const table of ['equipos','partidos','tabla_posiciones','tarifas_campeonato','transacciones_financieras','turnos_campeonato']) await pool.query('CREATE TABLE ' + table + ' (campeonato_id INTEGER)');
    await ensureAccessSchema(pool);
    await ensureAccessSchema(pool);
    admin = (await pool.query('INSERT INTO usuarios_sistema (nombre,email,password_hash,rol) VALUES ($1,$2,$3,$4) RETURNING id', ['Administrador de prueba','admin@example.test',await hashPassword(password),'admin'])).rows[0];
    await new Promise(resolve => { server = createApp(watchedPool).listen(0,'127.0.0.1',resolve); });

    await t.test('Rechaza acceso sin sesión y marcadores falsos', async () => {
      await expect('GET','/usuarios',null,undefined,401);
      await expect('GET','/campeonatos','session_active',undefined,401);
      await expect('POST','/auth/login',null,{email:'admin@example.test',password:'incorrecta'},401);
      adminToken = await login('admin@example.test');
      const current = await expect('GET','/auth/me',adminToken,undefined,200);
      assert.ok(current.user.permissions.includes('usuarios:gestionar'));
      assert.equal(current.user.password_hash,undefined);
    });
    await t.test('Guarda teléfono y correo de recuperación, sin exponer contraseñas', async () => {
      mesa = await createUser('mesa','mesa',{telefono:'+591 70000000',email_recuperacion:'alternativo@example.test'});
      referee = await createUser('arbitro','arbitro');
      anotherMesa = await createUser('mesa2','mesa');
      assert.equal(mesa.telefono,'+591 70000000'); assert.equal(mesa.email_recuperacion,'alternativo@example.test');
      const stored = (await pool.query('SELECT * FROM usuarios_sistema WHERE id=$1',[mesa.id])).rows[0];
      assert.match(stored.password_hash,/^scrypt\$/); assert.notEqual(stored.password_hash,password);
      const list = await expect('GET','/usuarios',adminToken,undefined,200);
      assert.ok(list.every(row => !('password_hash' in row) && !('password' in row)));
      await expect('POST','/usuarios',adminToken,{nombre:'Duplicado',email:'MESA@EXAMPLE.TEST',password,rol:'mesa'},409);
      await expect('POST','/usuarios',adminToken,{nombre:'Teléfono inválido',email:'invalid@example.test',password,rol:'mesa',telefono:'abc'},400);
      await expect('POST','/usuarios',adminToken,{nombre:'Correo inválido',email:'invalid@example.test',password,rol:'mesa',email_recuperacion:'incorrecto'},400);
      mesaToken = await login(mesa.email); refereeToken = await login(referee.email); anotherToken = await login(anotherMesa.email);
    });
    await t.test('Mesa y árbitro no pueden administrar usuarios ni ver auditoría', async () => {
      for (const token of [mesaToken,refereeToken]) {
        for (const [method,path,body] of [['GET','/usuarios'],['POST','/usuarios',{}],['PUT','/usuarios/'+admin.id,{}],['PATCH','/usuarios/'+admin.id+'/estado',{activo:false}],['DELETE','/usuarios/'+admin.id],['GET','/auditoria/campeonatos']]) await expect(method,path,token,body,403);
      }
    });
    await t.test('Administrador crea; mesa edita sin perder valores y no borra; árbitro solo consulta', async () => {
      championship = await expect('POST','/campeonatos',adminToken,championshipData,201);
      await expect('GET','/campeonatos/'+championship.id_campeonato,refereeToken,undefined,200);
      await expect('POST','/campeonatos',mesaToken,championshipData,403);
      await expect('DELETE','/campeonatos/'+championship.id_campeonato,mesaToken,undefined,403);
      for (const [method,path,body] of [['POST','/campeonatos',championshipData],['PUT','/campeonatos/'+championship.id_campeonato,{nombre:'No permitido'}],['DELETE','/campeonatos/'+championship.id_campeonato],['PUT','/partidos/1/resultados',{goles_local:3}]]) await expect(method,path,refereeToken,body,403);
      const updated = await expect('PUT','/campeonatos/'+championship.id_campeonato,mesaToken,{nombre:'Editado por mesa'},200);
      assert.equal(updated.campeonato.cantidad_canchas,3); assert.equal(updated.campeonato.descanso_entre_partidos_min,0); assert.equal(updated.campeonato.activo,false);
      const history = await expect('GET','/auditoria/campeonatos?campeonato_id='+championship.id_campeonato,adminToken,undefined,200);
      assert.equal(history.items[0].usuario_nombre,'mesa'); assert.equal(history.items[0].usuario_rol,'mesa');
      assert.deepEqual(history.items[0].detalles.cambios.nombre,{antes:'Copa de prueba',despues:'Editado por mesa'});
    });
    await t.test('La solicitud identifica a la sesión, no al solicitante enviado; solo muestra las propias', async () => {
      request = await expect('POST','/solicitudes-campeonato',mesaToken,{datos:{...championshipData,nombre:'Solicitado por mesa'},motivo:'Torneo de prueba',solicitante_id:admin.id,estado:'aprobada'},201);
      assert.equal(request.solicitante_id,mesa.id); assert.equal(request.estado,'pendiente');
      assert.equal((await pool.query('SELECT count(*)::int AS total FROM campeonatos')).rows[0].total,1);
      await expect('POST','/solicitudes-campeonato',mesaToken,{datos:championshipData},409);
      assert.equal((await expect('GET','/solicitudes-campeonato',anotherToken,undefined,200)).length,0);
      await expect('GET','/solicitudes-campeonato',refereeToken,undefined,403);
      await expect('PATCH','/solicitudes-campeonato/'+request.id,mesaToken,{decision:'aprobar'},403);
      await expect('POST','/solicitudes-campeonato',refereeToken,{datos:championshipData},403);
    });
    await t.test('Dos aprobaciones simultáneas crean exactamente un campeonato con el payload original', async () => {
      const answers = await Promise.all([call('PATCH','/solicitudes-campeonato/'+request.id,adminToken,{decision:'aprobar',datos:{nombre:'Manipulado'}}),call('PATCH','/solicitudes-campeonato/'+request.id,adminToken,{decision:'aprobar'})]);
      assert.deepEqual(answers.map(item => item.status).sort(),[200,409]);
      const created = answers.find(item => item.status===200).data.campeonato;
      assert.equal(created.nombre,'Solicitado por mesa');
      assert.equal((await pool.query('SELECT count(*)::int AS total FROM campeonatos')).rows[0].total,2);
      await expect('PATCH','/solicitudes-campeonato/'+request.id,adminToken,{decision:'aprobar'},409);
      await expect('POST','/campeonatos',mesaToken,championshipData,403);
    });
    await t.test('Rechazar no crea campeonatos y no permite una aprobación posterior', async () => {
      const pending = await expect('POST','/solicitudes-campeonato',mesaToken,{datos:championshipData},201);
      await expect('PATCH','/solicitudes-campeonato/'+pending.id,adminToken,{decision:'rechazar',respuesta:'No autorizado'},200);
      await expect('PATCH','/solicitudes-campeonato/'+pending.id,adminToken,{decision:'aprobar'},409);
      assert.equal((await pool.query('SELECT count(*)::int AS total FROM campeonatos')).rows[0].total,2);
    });
    await t.test('Activo/inactivo conserva contactos y revoca sesiones, sin reactivar tokens anteriores', async () => {
      const disabled = await expect('PATCH','/usuarios/'+mesa.id+'/estado',adminToken,{activo:false,rol:'admin'},200);
      assert.equal(disabled.telefono,mesa.telefono); assert.equal(disabled.email_recuperacion,mesa.email_recuperacion); assert.equal(disabled.role,'mesa');
      const contactEdit = await expect('PUT','/usuarios/'+mesa.id,adminToken,{telefono:'+591 70000009'},200);
      assert.equal(contactEdit.activo,false); assert.equal(contactEdit.role,'mesa'); assert.equal(contactEdit.email_recuperacion,mesa.email_recuperacion);
      await expect('GET','/auth/me',mesaToken,undefined,401);
      await expect('POST','/auth/login',null,{email:mesa.email,password},401);
      await expect('PATCH','/usuarios/'+mesa.id+'/estado',adminToken,{activo:true},200);
      await expect('GET','/auth/me',mesaToken,undefined,401);
      mesaToken=await login(mesa.email);
    });
    await t.test('Cambiar rol y contraseña invalida sesiones; la contraseña es opcional al editar', async () => {
      await expect('PUT','/usuarios/'+referee.id,adminToken,{nombre:'Mesa convertida',email:referee.email,rol:'mesa',activo:true,telefono:'70000001',email_recuperacion:'backup@example.test'},200);
      await expect('GET','/auth/me',refereeToken,undefined,401);
      const fresh = await login(referee.email);
      const me = await expect('GET','/auth/me',fresh,undefined,200); assert.equal(me.user.role,'mesa');
      await expect('PUT','/usuarios/'+referee.id,adminToken,{nombre:'Mesa convertida',email:referee.email,rol:'mesa',activo:true,password:'Password-new-42!'},200);
      await expect('GET','/auth/me',fresh,undefined,401);
      await expect('POST','/auth/login',null,{email:referee.email,password},401);
      await expect('POST','/auth/login',null,{email:referee.email,password:'Password-new-42!'},200);
    });
    await t.test('Revoca una petición autenticada antes de que escriba', async () => {
      const lock=await pool.connect();
      try {
        await lock.query('BEGIN'); await lock.query('SELECT pg_advisory_xact_lock(91840621)');
        const authenticated = new Promise(resolve => { observer={hash:digest(anotherToken),resolve}; });
        const pending = call('PUT','/campeonatos/'+championship.id_campeonato,anotherToken,{nombre:'No debe guardarse'});
        await authenticated;
        await lock.query('UPDATE usuarios_sistema SET activo=false WHERE id=$1',[anotherMesa.id]);
        await lock.query('DELETE FROM sesiones_usuario WHERE usuario_id=$1',[anotherMesa.id]);
        await lock.query('COMMIT');
        assert.equal((await pending).status,401);
        assert.equal((await pool.query('SELECT nombre FROM campeonatos WHERE id_campeonato=$1',[championship.id_campeonato])).rows[0].nombre,'Editado por mesa');
      } finally { await lock.query('ROLLBACK'); lock.release(); observer=null; }
    });
    await t.test('Eliminar retira el acceso y el listado, conserva autoría y bloquea solicitudes del eliminado', async () => {
      const pending = await expect('POST','/solicitudes-campeonato',mesaToken,{datos:championshipData},201);
      await expect('DELETE','/usuarios/'+mesa.id,adminToken,undefined,200);
      assert.ok(!(await expect('GET','/usuarios',adminToken,undefined,200)).some(item=>item.id===mesa.id));
      await expect('GET','/auth/me',mesaToken,undefined,401);
      await expect('POST','/auth/login',null,{email:mesa.email,password},401);
      await expect('PATCH','/usuarios/'+mesa.id+'/estado',adminToken,{activo:true},404);
      await expect('PATCH','/solicitudes-campeonato/'+pending.id,adminToken,{decision:'aprobar'},409);
      const history=await expect('GET','/auditoria/campeonatos',adminToken,undefined,200);
      assert.equal(history.items[0].usuario_nombre,'mesa');
      await expect('PATCH','/solicitudes-campeonato/'+pending.id,adminToken,{decision:'rechazar'},200);
    });
    await t.test('Protege la cuenta propia y conserva un administrador ante cambios simultáneos', async () => {
      await expect('DELETE','/usuarios/'+admin.id,adminToken,undefined,409);
      await expect('PATCH','/usuarios/'+admin.id+'/estado',adminToken,{activo:false},409);
      await expect('PUT','/usuarios/'+admin.id,adminToken,{nombre:'Admin',email:'admin@example.test',rol:'mesa',activo:true},409);
      const a=await createUser('admin2','admin'); const b=await createUser('admin3','admin');
      const aToken=await login(a.email); const bToken=await login(b.email);
      const outcomes=await Promise.all([call('DELETE','/usuarios/'+b.id,aToken),call('DELETE','/usuarios/'+a.id,bToken)]);
      assert.equal(outcomes.filter(item=>item.status===200).length,1);
      assert.ok(outcomes.some(item=>[401,403].includes(item.status)));
      assert.ok((await pool.query("SELECT count(*)::int AS total FROM usuarios_sistema WHERE activo AND eliminado_at IS NULL AND rol='admin'")).rows[0].total>=1);
    });
    await t.test('Logout y expiración invalidan tokens en PostgreSQL', async () => {
      const temp=await createUser('sesion','mesa'); const token=await login(temp.email);
      await expect('POST','/auth/logout',token,{},200); await expect('GET','/auth/me',token,undefined,401);
      const expired=await login(temp.email);
      await pool.query("UPDATE sesiones_usuario SET expira_at=NOW()-INTERVAL '1 second' WHERE token_hash=$1",[digest(expired)]);
      await expect('GET','/auth/me',expired,undefined,401);
    });
    await t.test('Actualiza contraseñas antiguas tras login válido sin cambiarlas', async () => {
      await pool.query('INSERT INTO usuarios_sistema (nombre,email,password_hash,rol) VALUES ($1,$2,$3,$4)',['Antiguo','legacy@example.test',password,'mesa']);
      await login('legacy@example.test');
      assert.match((await pool.query('SELECT password_hash FROM usuarios_sistema WHERE email=$1',['legacy@example.test'])).rows[0].password_hash,/^scrypt\$/);
    });
  } finally {
    if (server) await new Promise(resolve=>server.close(resolve));
    await pool.end();
    // Only this test's freshly created, validated schema is removed.
    assert.match(schema,/^arena_access_test_\d+_[a-f0-9]{10}$/);
    try { await maintenance.query('DROP SCHEMA IF EXISTS ' + schema + ' CASCADE'); }
    finally { await maintenance.end(); await configurationPool.end(); }
  }
});
