const test = require('node:test');
const assert = require('node:assert/strict');
const { randomBytes } = require('node:crypto');
const { Pool } = require('pg');
const { pool: configurationPool } = require('../config/db');
const { createApp } = require('../src/app');
const { ensureAccessSchema } = require('../src/security/schema');
const { hashPassword, digest, verifyPassword } = require('../src/security/access');

test('Recuperación con aprobación, clave temporal y cambio obligatorio', { timeout: 120000 }, async t => {
  const schema = 'arena_recovery_test_' + process.pid + '_' + randomBytes(5).toString('hex');
  assert.match(schema, /^arena_recovery_test_\d+_[a-f0-9]{10}$/);
  const options = { ...configurationPool.options, password: configurationPool.options.password };
  const maintenance = new Pool({ ...options, max: 1 });
  const pool = new Pool({ ...options, options: '-c search_path=' + schema, max: 8 });
  const password = 'Arena-test-928!';
  const nextPassword = ' Nueva clave personal 45! ';
  const temporary = '12345678';
  const app = createApp(pool);
  let server, adminToken, passwordHash, serial = 0;
  async function call(method, path, body, token, instance = server, headers = {}) {
    const response = await fetch('http://127.0.0.1:' + instance.address().port + '/api' + path, {
      method, headers: { ...headers, 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) },
      body: body === undefined ? undefined : JSON.stringify(body), signal: AbortSignal.timeout(10000),
    });
    return { status: response.status, data: await response.json(), cache: response.headers.get('cache-control') };
  }
  async function user(extra = {}) {
    const data = {nombre:'Prueba ' + (++serial),email:'test'+serial+'@example.test',rol:'mesa',activo:true,...extra};
    return (await pool.query('INSERT INTO usuarios_sistema (nombre,email,password_hash,rol,activo,eliminado_at) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *', [data.nombre,data.email,passwordHash,data.rol,data.activo,data.eliminado_at || null])).rows[0];
  }
  const login = (account, pass = password) => call('POST','/auth/login',{email:account.email,password:pass});
  const stored = async account => (await pool.query('SELECT * FROM usuarios_sistema WHERE id=$1',[account.id])).rows[0];
  const change = (token, data = {}) => call('POST','/auth/change-password',{password:nextPassword,confirmPassword:nextPassword,...data},token);
  const decide = (id, decision = 'aprobar', token = adminToken) => call('PATCH','/solicitudes-recuperacion/'+id,{decision,respuesta:'Revisado en persona'},token);
  async function request(account, data = {}, headers = {}) {
    const result = await call('POST','/auth/forgot-password',{usuario:account.email,...data},undefined,server,headers);
    assert.equal(result.status,202);
    return (await pool.query("SELECT * FROM solicitudes_recuperacion WHERE usuario_id=$1 AND estado='pendiente'",[account.id])).rows[0];
  }
  async function approve(account) {
    const entry = await request(account);
    const result = await decide(entry.id);
    assert.equal(result.status,200,result.data.error);
    return entry;
  }
  t.beforeEach(async () => { await pool.query('DELETE FROM limites_recuperacion'); });
  try {
    await maintenance.query('CREATE SCHEMA ' + schema);
    await pool.query(`
      CREATE TABLE usuarios_sistema (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,nombre VARCHAR(100) NOT NULL,email VARCHAR(150) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,rol VARCHAR(50) NOT NULL,activo BOOLEAN DEFAULT true,created_at TIMESTAMP DEFAULT NOW());
      CREATE TABLE campeonatos (id_campeonato INTEGER PRIMARY KEY);
      CREATE TABLE auditoria_logs (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,usuario_id INTEGER REFERENCES usuarios_sistema(id),accion VARCHAR(100),detalles JSONB,ip_origen VARCHAR(45),created_at TIMESTAMP DEFAULT NOW());
    `);
    await ensureAccessSchema(pool); await ensureAccessSchema(pool);
    passwordHash = await hashPassword(password);
    const admin = await user({rol:'admin'});
    await new Promise(resolve => { server = app.listen(0,'127.0.0.1',resolve); });
    adminToken = (await login(admin)).data.token;

    await t.test('Solicitar no cambia la contraseña; cuenta sin correo alternativo funciona y la respuesta es genérica', async () => {
      const active = await user(); const session = (await login(active)).data.token;
      const accounts = [active,{email:'unknown@example.test'},await user({activo:false}),await user({eliminado_at:new Date()})];
      let expected;
      for (const account of accounts) {
        const result = await call('POST','/auth/forgot-password',{usuario:account.email});
        assert.equal(result.status,202); assert.equal(result.cache,'no-store');
        expected ||= result.data; assert.deepEqual(result.data,expected);
        assert.deepEqual(Object.keys(result.data),['message']);
      }
      const pending = await pool.query('SELECT * FROM solicitudes_recuperacion');
      assert.equal(pending.rowCount,1); assert.equal(pending.rows[0].usuario_id,active.id);
      assert.equal((await stored(active)).password_hash,passwordHash);
      assert.equal((await call('GET','/auth/me',undefined,session)).status,200);
    });
    await t.test('Deduplica pendientes, normaliza el usuario y descarta identidad/estado manipulados', async () => {
      const account = await user();
      const entry = await request(account,{usuario:'  '+account.email.toUpperCase()+'  ',usuario_id:admin.id,estado:'aprobada',nombre:'Falso',created_at:'2000-01-01T00:00:00.000Z',ip_origen:'203.0.113.99',ip:'203.0.113.99'});
      const again = await request(account);
      assert.notEqual(entry.created_at.toISOString(),'2000-01-01T00:00:00.000Z');
      assert.equal(entry.id,again.id); assert.equal(entry.usuario_id,account.id); assert.equal(entry.email_usuario,account.email); assert.equal(entry.estado,'pendiente');
      const list = await call('GET','/solicitudes-recuperacion',undefined,adminToken);
      assert.equal(list.status,200);
      const listed=list.data.find(item=>item.id===entry.id);
      assert.equal(listed.solicitante_nombre,account.nombre);
      assert.equal(listed.created_at,entry.created_at.toISOString());
      assert.equal(listed.resuelta_at,null);
      assert.equal(entry.ip_origen,'127.0.0.1');
      assert.equal(listed.ip_origen,entry.ip_origen);
      assert.ok(!JSON.stringify(list.data).includes(passwordHash));
    });
    await t.test('Guarda IPv4/IPv6 del proxy local y conserva el origen al reenviar y resolver', async () => {
      const cases = [
        ['198.51.100.24','198.51.100.24'],
        ['::ffff:192.0.2.10','192.0.2.10'],
        ['2001:db8:1234:5678:abcd:ef01:2345:6789','2001:db8:1234:5678:abcd:ef01:2345:6789'],
        ['203.0.113.99, 198.51.100.26','198.51.100.26'],
        ['direccion-invalida',null],
      ];
      for (const [forwarded, expected] of cases) {
        const account = await user();
        const entry = await request(account,{ip_origen:'203.0.113.99'}, {'X-Forwarded-For':forwarded});
        assert.equal(entry.ip_origen,expected);
        const again = await request(account,{}, {'X-Forwarded-For':'192.0.2.50'});
        assert.equal(again.id,entry.id);
        assert.equal(again.ip_origen,expected);
        assert.equal(again.created_at.toISOString(),entry.created_at.toISOString());
        const list = await call('GET','/solicitudes-recuperacion',undefined,adminToken);
        assert.equal(list.data.find(item=>item.id===entry.id).ip_origen,expected);
        const decision = expected?.includes(':') ? 'rechazar' : 'aprobar';
        const resolved = await call('PATCH','/solicitudes-recuperacion/'+entry.id,{decision,ip_origen:'203.0.113.99'},adminToken,server,{'X-Forwarded-For':'198.51.100.200'});
        assert.equal(resolved.status,200,resolved.data.error);
        assert.equal(resolved.data.solicitud.ip_origen,expected);
        const stored = (await pool.query('SELECT ip_origen,created_at FROM solicitudes_recuperacion WHERE id=$1',[entry.id])).rows[0];
        assert.equal(stored.ip_origen,expected);
        assert.equal(stored.created_at.toISOString(),entry.created_at.toISOString());
      }
    });
    await t.test('Los registros antiguos sin IP siguen disponibles después de repetir la migración', async () => {
      const account = await user();
      const entry = (await pool.query('INSERT INTO solicitudes_recuperacion (usuario_id,email_usuario) VALUES ($1,$2) RETURNING *',[account.id,account.email])).rows[0];
      await ensureAccessSchema(pool);
      const listed = (await call('GET','/solicitudes-recuperacion',undefined,adminToken)).data.find(item=>item.id===entry.id);
      assert.equal(listed.ip_origen,null);
      assert.equal(listed.created_at,entry.created_at.toISOString());
      assert.equal((await decide(entry.id,'rechazar')).status,200);
    });
    await t.test('Solo un administrador con sesión vigente puede consultar y resolver recuperaciones', async () => {
      const account = await user(); const entry = await request(account);
      assert.equal((await call('GET','/solicitudes-recuperacion')).status,401);
      for (const rol of ['mesa','arbitro']) {
        const token = (await login(await user({rol}))).data.token;
        assert.equal((await call('GET','/solicitudes-recuperacion',undefined,token)).status,403);
        assert.equal((await decide(entry.id,'aprobar',token)).status,403);
        assert.equal((await decide(entry.id,'rechazar',token)).status,403);
      }
      assert.equal((await stored(account)).password_hash,passwordHash);
    });
    await t.test('Rechazar conserva la contraseña y no permite aprobar después la misma solicitud', async () => {
      const account = await user(); const entry = await request(account);
      assert.equal((await decide(entry.id,'rechazar')).status,200);
      assert.equal((await decide(entry.id)).status,409);
      assert.equal((await stored(account)).password_hash,passwordHash);
      assert.equal((await login(account)).status,200);
      assert.equal((await login(account,temporary)).status,401);
    });
    await t.test('Dos aprobaciones simultáneas producen una sola aprobación y revocan las sesiones anteriores', async () => {
      const account = await user(); const session = (await login(account)).data.token;
      const entry = await request(account);
      const answers = await Promise.all([decide(entry.id),decide(entry.id)]);
      assert.deepEqual(answers.map(item=>item.status).sort(),[200,409]);
      const row = await stored(account);
      assert.ok(await verifyPassword(temporary,row.password_hash)); assert.notEqual(row.password_hash,temporary);
      assert.equal(row.debe_cambiar_password,true); assert.ok(row.password_temporal_expira_at>Date.now());
      assert.equal((await call('GET','/auth/me',undefined,session)).status,401);
      assert.equal((await login(account)).status,401);
    });
    await t.test('La sesión temporal solo puede consultar su identidad, cerrar sesión o cambiar la contraseña', async () => {
      const account = await user(); await approve(account);
      const result = await login(account,temporary);
      assert.equal(result.status,200); assert.equal(result.data.user.requiresPasswordChange,true); assert.deepEqual(result.data.user.permissions,[]);
      const token = result.data.token;
      assert.equal((await call('GET','/auth/me',undefined,token)).data.user.requiresPasswordChange,true);
      for (const [method,path,body] of [['GET','/campeonatos'],['GET','/solicitudes-campeonato'],['GET','/solicitudes-recuperacion'],['GET','/usuarios'],['GET','/auditoria/campeonatos'],['POST','/campeonatos',{}],['PUT','/usuarios/'+account.id,{}],['POST','/solicitudes-campeonato',{}],['PUT','/partidos/1/resultados',{}]]) assert.equal((await call(method,path,body,token)).status,403,method+' '+path);
      assert.equal((await call('POST','/auth/logout',{},token)).status,200);
      assert.equal((await call('GET','/auth/me',undefined,token)).status,401);
    });
    await t.test('Exige confirmación, longitud válida y una clave distinta de 12345678', async () => {
      const account = await user(); await approve(account); const token = (await login(account,temporary)).data.token;
      for (const data of [{password:'corta',confirmPassword:'corta'},{confirmPassword:'Distinta123'},{password:temporary,confirmPassword:temporary},{password:'x'.repeat(129),confirmPassword:'x'.repeat(129)}]) assert.equal((await change(token,data)).status,400);
      assert.equal((await stored(account)).debe_cambiar_password,true);
      assert.equal((await call('GET','/auth/me',undefined,token)).status,200);
      assert.equal((await change(adminToken)).status,409);
    });
    await t.test('El cambio atómico consume todas las sesiones temporales y emite una nueva sesión normal', async () => {
      const account = await user(); await approve(account);
      const first = (await login(account,temporary)).data.token;
      const second = (await login(account,temporary)).data.token;
      const results = await Promise.all([change(first,{usuario_id:admin.id}),change(second)]);
      assert.deepEqual(results.map(item=>item.status).sort(),[200,401]);
      const data = results.find(item=>item.status===200).data;
      assert.equal(data.user.id,account.id); assert.equal(data.user.requiresPasswordChange,false); assert.ok(data.user.permissions.includes('campeonatos:ver'));
      for (const token of [first,second]) assert.equal((await call('GET','/auth/me',undefined,token)).status,401);
      assert.equal((await call('GET','/campeonatos',undefined,data.token)).status,200);
      assert.equal((await login(account,temporary)).status,401); assert.equal((await login(account,nextPassword)).status,200);
      assert.ok(await verifyPassword(nextPassword,(await stored(account)).password_hash));
      assert.equal((await login(admin)).status,200);
      const logs = (await pool.query("SELECT detalles FROM auditoria_logs WHERE accion='password_cambiado_por_titular' AND usuario_id=$1",[account.id])).rows;
      assert.equal(logs.length,1); assert.ok(!JSON.stringify(logs).includes(nextPassword));
    });
    await t.test('La temporal vence y una nueva aprobación vuelve a habilitar la recuperación', async () => {
      const account = await user(); await approve(account); const token = (await login(account,temporary)).data.token;
      await pool.query("UPDATE usuarios_sistema SET password_temporal_expira_at=clock_timestamp()-INTERVAL '1 second' WHERE id=$1",[account.id]);
      assert.equal((await login(account,temporary)).status,401);
      assert.equal((await change(token)).status,401);
      await approve(account); assert.equal((await login(account,temporary)).status,200);
    });
    await t.test('Aprobar levanta el bloqueo causado por intentos con la contraseña olvidada', async () => {
      const account = await user();
      for (let i=0;i<10;i++) assert.equal((await login(account,'incorrecta')).status,401);
      assert.equal((await login(account)).status,429);
      await approve(account); assert.equal((await login(account,temporary)).status,200);
    });
    await t.test('Cambiar credenciales, rol o estado cancela solicitudes anteriores sin reactivarlas', async () => {
      const cases = [['PUT','',{email:'changed@example.test'}],['PUT','',{password:'Clave del admin 98!'}],['PUT','',{rol:'arbitro'}],['PATCH','/estado',{activo:false}],['DELETE','',undefined]];
      for (const [method,suffix,data] of cases) {
        const account = await user(); const entry = await request(account);
        assert.equal((await call(method,'/usuarios/'+account.id+suffix,data,adminToken)).status,200);
        assert.equal((await decide(entry.id)).status,409);
        const row=(await pool.query('SELECT estado FROM solicitudes_recuperacion WHERE id=$1',[entry.id])).rows[0];
        assert.equal(row.estado,'cancelada');
      }
    });
    await t.test('Editar teléfono no quita la obligación; desactivar y reactivar no recupera la temporal anterior', async () => {
      const account = await user(); await approve(account); const token=(await login(account,temporary)).data.token;
      const list=await call('GET','/usuarios',undefined,adminToken);
      assert.equal(list.data.find(item=>item.id===account.id).requiresPasswordChange,true);
      const edited=await call('PUT','/usuarios/'+account.id,{telefono:'+591 70000000'},adminToken);
      assert.equal(edited.status,200); assert.equal(edited.data.requiresPasswordChange,true);
      assert.equal((await call('GET','/auth/me',undefined,token)).data.user.requiresPasswordChange,true);
      assert.equal((await call('PATCH','/usuarios/'+account.id+'/estado',{activo:false},adminToken)).status,200);
      assert.equal((await call('PATCH','/usuarios/'+account.id+'/estado',{activo:true},adminToken)).status,200);
      assert.equal((await login(account,temporary)).status,401);
      await approve(account);
      assert.equal((await call('PUT','/usuarios/'+account.id,{password:'Nueva por admin 789!'},adminToken)).status,200);
      assert.equal((await login(account,'Nueva por admin 789!')).data.user.requiresPasswordChange,false);
    });
    await t.test('Un administrador recuperado también queda restringido y no puede aprobarse a sí mismo', async () => {
      const target = await user({rol:'admin'}); const session=(await login(target)).data.token;
      const entry=await request(target);
      assert.equal((await decide(entry.id,'aprobar',session)).status,409);
      assert.equal((await decide(entry.id)).status,200);
      const temporarySession=(await login(target,temporary)).data.token;
      assert.equal((await call('GET','/usuarios',undefined,temporarySession)).status,403);
      assert.equal((await call('GET','/solicitudes-recuperacion',undefined,temporarySession)).status,403);
      assert.equal((await change(temporarySession)).status,200);
    });
    await t.test('El fallo de auditoría revierte aprobación y cambio definitivo completos', async () => {
      const account=await user(); const entry=await request(account); const session=(await login(account)).data.token;
      async function fail(action, operation) {
        await pool.query(`CREATE FUNCTION fail_recovery_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.accion='${action}' THEN RAISE EXCEPTION 'Simulated audit failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_recovery BEFORE INSERT ON auditoria_logs FOR EACH ROW EXECUTE FUNCTION fail_recovery_audit();`);
        try { await operation(); } finally { await pool.query('DROP TRIGGER fail_recovery ON auditoria_logs; DROP FUNCTION fail_recovery_audit()'); }
      }
      await fail('recuperacion_aprobada',async()=>{
        assert.equal((await decide(entry.id)).status,500);
        assert.equal((await stored(account)).password_hash,passwordHash);
        assert.equal((await call('GET','/auth/me',undefined,session)).status,200);
      });
      assert.equal((await decide(entry.id)).status,200);
      const token=(await login(account,temporary)).data.token;
      await fail('password_cambiado_por_titular',async()=>{
        assert.equal((await change(token)).status,500);
        assert.equal((await stored(account)).debe_cambiar_password,true);
        assert.equal((await call('GET','/auth/me',undefined,token)).status,200);
      });
      assert.equal((await change(token)).status,200);
    });
    await t.test('Los enlaces de correo anteriores no eluden la nueva aprobación', async () => {
      const account=await user(); const token=randomBytes(32).toString('base64url');
      await pool.query("INSERT INTO recuperaciones_password (token_hash,usuario_id,email_recuperacion,expira_at) VALUES ($1,$2,'old@example.test',clock_timestamp()+INTERVAL '1 hour')",[digest(token),account.id]);
      assert.equal((await call('POST','/auth/reset-password',{token,password:nextPassword,confirmPassword:nextPassword})).status,410);
      assert.equal((await stored(account)).password_hash,passwordHash);
      await approve(account);
      assert.equal((await pool.query('SELECT 1 FROM recuperaciones_password WHERE usuario_id=$1',[account.id])).rowCount,0);
    });
    await t.test('Los límites por usuario persisten entre instancias y no duplican notificaciones', async () => {
      const account=await user(); for(let i=0;i<3;i++) await request(account);
      const otherServer=await new Promise(resolve=>{const instance=createApp(pool).listen(0,'127.0.0.1',()=>resolve(instance));});
      try { assert.equal((await call('POST','/auth/forgot-password',{usuario:account.email},null,otherServer)).status,429); }
      finally { await new Promise(resolve=>otherServer.close(resolve)); }
      assert.equal((await pool.query('SELECT count(*)::int AS total FROM solicitudes_recuperacion WHERE usuario_id=$1',[account.id])).rows[0].total,1);
    });
  } finally {
    if (server) await new Promise(resolve => server.close(resolve));
    await pool.end();
    await maintenance.query('DROP SCHEMA IF EXISTS ' + schema + ' CASCADE');
    await maintenance.end(); await configurationPool.end();
  }
});
